In [1]:
import numpy as np

In [2]:
state = {
    0: "Healthy State",
    1: "Progression",
    2: "Death"
}

In [3]:
print(state)

{0: 'Healthy State', 1: 'Progression', 2: 'Death'}


In [4]:
possibilities = np.array([[0.3, 0.4,0.3], [0.3,0,0.7], [0.5,0,0.5]])

In [5]:
possibilities

array([[0.3, 0.4, 0.3],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

In [14]:
n = 15
first_state = 0
current_state = start_state
print(state[current_state], "-", end="**")

while n-1:
    current_state = np.random.choice([0, 1, 2], p=possibilities[current_state])
    print(state[current_state], "-", end="**")
    n-=1
print("done")

Healthy State -**Progression -**Death -**Death -**Death -**Death -**Healthy State -**Death -**Healthy State -**Death -**Healthy State -**Progression -**Death -**Healthy State -**Healthy State -**done


In [15]:
steps = 10**6
first_state = 0
current_state = first_state
prob = np.array([0, 0, 0])
prob[first_state] = 1

i = 0
while i<steps:
    current_state = np.random.choice([0,1,2], p=possibilities[current_state])
    prob[current_state]+=1
    i +=1

print("prob = ", prob/steps)

prob =  [0.390206 0.156409 0.453386]


In [10]:
steps = 10**3
possibilities_n = possibilities

i=0
while i<steps:
    possibilities_n =  np.matmul(possibilities_n, possibilities)
    i+=1

print("possibilities^n = \n", possibilities_n, "\n")
print("c = ", possibilities_n[0])

possibilities^n = 
 [[0.390625 0.15625  0.453125]
 [0.390625 0.15625  0.453125]
 [0.390625 0.15625  0.453125]] 

c =  [0.390625 0.15625  0.453125]


In [16]:
import scipy.linalg
values, left = scipy.linalg.eig(possibilities, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[ 0.63174837+0.j          0.15811388+0.41833001j  0.15811388-0.41833001j]
 [ 0.25269935+0.j         -0.63245553+0.j         -0.63245553-0.j        ]
 [ 0.73282811+0.j          0.47434165-0.41833001j  0.47434165+0.41833001j]] 

eigen values = 
 [ 1. +0.j         -0.1+0.26457513j -0.1-0.26457513j]


In [17]:
possib = left[:,0]
possib_normal = [(x/np.sum(possib)).real for x in possib]
possib_normal

[0.3906249999999997, 0.15625000000000044, 0.4531249999999997]

In [18]:
def find_possib(seq, possibilities, possib):
    first_state = seq[0]
    possib_x = possib[start_state]
    prev_state, current_state = first_state, first_state
    for i in range(1, len(seq)):
        current_state = seq[i]
        possib_x *= possibilities[prev_state][current_state]
        prev_state = current_state
    return possib_x

print(find_possib([1, 2, 2, 0], possibilities, possib_normal))

0.06835937499999994
